/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an INFO or CANCELLATION post (ORG audience: admins; COACH_STUDENTS: coaches) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/poster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a POSTER post with an image (content-sniffed JPEG/PNG/WebP, max 5 MB) */
        post: operations["createPoster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{memberId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending member (admins only) */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new account, creating or joining an organization */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password (server session cookie) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{memberId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change a member's role (admins only, OWNER excluded) */
        patch: operations["changeRole"];
        trace?: never;
    };
    "/api/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active members of the caller's organization */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List members awaiting approval (admins only) */
        get: operations["listPendingMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated feed of the caller: ORG posts plus COACH_STUDENTS posts they can see */
        get: operations["feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user profile */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prime the CSRF cookie and return the current token */
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a post (author or admins) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePostRequest: {
            /**
             * @description INFO or CANCELLATION — posters go through POST /api/posts/poster
             * @enum {string}
             */
            type: "INFO" | "CANCELLATION" | "POSTER";
            /** @enum {string} */
            audience: "ORG" | "COACH_STUDENTS";
            title: string;
            body?: string;
        };
        FeedPostResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            type?: "INFO" | "CANCELLATION" | "POSTER";
            /** @enum {string} */
            audience?: "ORG" | "COACH_STUDENTS";
            title?: string;
            body?: string;
            /** @description Short-lived signed URL of the poster image (POSTER posts only) */
            imageUrl?: string;
            /** Format: uuid */
            authorId?: string;
            authorDisplayName?: string;
            /** @enum {string} */
            authorRole?: "OWNER" | "ADMIN" | "COACH" | "MEMBER";
            /** Format: date-time */
            createdAt?: string;
        };
        CreatePosterRequest: {
            /** @enum {string} */
            audience: "ORG" | "COACH_STUDENTS";
            title: string;
            body?: string;
        };
        MemberResponse: {
            /** Format: uuid */
            id?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "COACH" | "MEMBER";
        };
        CreateOrganization: {
            name: string;
            /** @enum {string} */
            climbingType: "BOULDER" | "ROPES" | "BOTH";
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            displayName: string;
            createOrganization?: components["schemas"]["CreateOrganization"];
            /** @description Slug of the organization to join as a pending member */
            joinSlug?: string;
            createMode?: boolean;
            joinMode?: boolean;
        };
        MeResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "COACH" | "MEMBER";
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "DISABLED";
            organization?: components["schemas"]["OrganizationSummary"];
        };
        OrganizationSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            slug?: string;
            /** @enum {string} */
            climbingType?: "BOULDER" | "ROPES" | "BOTH";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UpdateRoleRequest: {
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "COACH" | "MEMBER";
        };
        PendingMemberResponse: {
            /** Format: uuid */
            id?: string;
            displayName?: string;
            email?: string;
        };
        FeedPageResponse: {
            items?: components["schemas"]["FeedPostResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            hasNext?: boolean;
        };
        CsrfToken: {
            parameterName?: string;
            token?: string;
            headerName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPostResponse"];
                };
            };
            /** @description Role not allowed to publish to the requested audience */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPostResponse"];
                };
            };
        };
    };
    createPoster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    meta: components["schemas"]["CreatePosterRequest"];
                    /** Format: binary */
                    image: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPostResponse"];
                };
            };
            /** @description File content is not a supported image */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPostResponse"];
                };
            };
            /** @description Role not allowed to publish to the requested audience */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPostResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member not found in the caller's organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Member is not pending */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and session established */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
            /** @description joinSlug does not match any organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Member not found in the caller's organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"][];
                };
            };
        };
    };
    listPendingMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PendingMemberResponse"][];
                };
            };
        };
    };
    feed: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPageResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query: {
                token: components["schemas"]["CsrfToken"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found in the caller's organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
